import React from 'react';
import Icon from '../../../components/AppIcon';
import Button from '../../../components/ui/Button';

const ReportJobsTable = ({ jobs, loading, onDownload, onApprove, currentUserId }) => {
  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString)?.toLocaleDateString('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getStatusBadge = (status) => {
    const statusConfig = {
      pending: { label: 'Pending', className: 'bg-warning/10 text-warning border-warning' },
      in_progress: { label: 'In Progress', className: 'bg-primary/10 text-primary border-primary' },
      completed: { label: 'Completed', className: 'bg-success/10 text-success border-success' },
      failed: { label: 'Failed', className: 'bg-destructive/10 text-destructive border-destructive' }
    };

    const config = statusConfig?.[status] || statusConfig?.pending;

    return (
      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${config?.className}`}>
        {config?.label}
      </span>
    );
  };

  if (loading) {
    return (
      <div className="bg-card rounded-lg border border-border p-8 text-center">
        <Icon name="Loader" size={32} className="animate-spin mx-auto mb-2 text-muted-foreground" />
        <p className="text-sm text-muted-foreground">Loading reporting jobs...</p>
      </div>
    );
  }

  if (jobs?.length === 0) {
    return (
      <div className="bg-card rounded-lg border border-border p-8 text-center">
        <Icon name="FileText" size={48} className="mx-auto mb-4 text-muted-foreground" />
        <p className="text-sm text-muted-foreground">No reporting jobs found. Generate your first report to get started.</p>
      </div>
    );
  }

  return (
    <div className="bg-card rounded-lg border border-border overflow-hidden">
      {/* Desktop Table View */}
      <div className="hidden lg:block overflow-x-auto">
        <table className="w-full">
          <thead className="bg-muted/50 border-b border-border">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Report Name
              </th>
              <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Reporting Year
              </th>
              <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Status
              </th>
              <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Generated By
              </th>
              <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Generated At
              </th>
              <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Approved By
              </th>
              <th className="px-4 py-3 text-right text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {jobs?.map((job) => (
              <tr key={job?.id} className="hover:bg-muted/30 transition-all duration-200 hover:shadow-sm">
                <td className="px-4 py-4">
                  <p className="text-sm font-medium text-foreground">{job?.job_name}</p>
                </td>
                <td className="px-4 py-4">
                  <p className="text-sm text-foreground">{job?.reporting_years?.year || 'N/A'}</p>
                </td>
                <td className="px-4 py-4">
                  {getStatusBadge(job?.status)}
                </td>
                <td className="px-4 py-4">
                  <p className="text-sm text-foreground">{job?.generator?.full_name || 'N/A'}</p>
                  <p className="text-xs text-muted-foreground">{job?.generator?.email || ''}</p>
                </td>
                <td className="px-4 py-4">
                  <p className="text-sm text-foreground">{formatDate(job?.generated_at)}</p>
                </td>
                <td className="px-4 py-4">
                  {job?.approved_by ? (
                    <>
                      <p className="text-sm text-foreground">{job?.approver?.full_name || 'N/A'}</p>
                      <p className="text-xs text-muted-foreground">{formatDate(job?.approved_at)}</p>
                    </>
                  ) : (
                    <p className="text-sm text-muted-foreground">Pending</p>
                  )}
                </td>
                <td className="px-4 py-4 text-right">
                  <div className="flex items-center justify-end gap-2">
                    {job?.status === 'completed' && (
                      <Button
                        variant="ghost"
                        size="sm"
                        iconName="Download"
                        onClick={() => onDownload(job)}
                      >
                        Download
                      </Button>
                    )}
                    {job?.status === 'pending' && job?.generated_by !== currentUserId && !job?.approved_by && (
                      <Button
                        variant="default"
                        size="sm"
                        iconName="CheckCircle"
                        onClick={() => onApprove(job?.id)}
                      >
                        Approve
                      </Button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Mobile Card View */}
      <div className="lg:hidden divide-y divide-border">
        {jobs?.map((job) => (
          <div key={job?.id} className="p-4">
            <div className="flex items-start justify-between mb-3">
              <div className="flex-1">
                <p className="text-sm font-medium text-foreground mb-1">{job?.job_name}</p>
                <p className="text-xs text-muted-foreground">Year: {job?.reporting_years?.year || 'N/A'}</p>
              </div>
              {getStatusBadge(job?.status)}
            </div>

            <div className="space-y-2 mb-3">
              <div>
                <p className="text-xs text-muted-foreground">Generated By</p>
                <p className="text-sm text-foreground">{job?.generator?.full_name || 'N/A'}</p>
                <p className="text-xs text-muted-foreground">{formatDate(job?.generated_at)}</p>
              </div>

              {job?.approved_by && (
                <div>
                  <p className="text-xs text-muted-foreground">Approved By</p>
                  <p className="text-sm text-foreground">{job?.approver?.full_name || 'N/A'}</p>
                  <p className="text-xs text-muted-foreground">{formatDate(job?.approved_at)}</p>
                </div>
              )}
            </div>

            <div className="flex gap-2">
              {job?.status === 'completed' && (
                <Button
                  variant="ghost"
                  size="sm"
                  iconName="Download"
                  onClick={() => onDownload(job)}
                  fullWidth
                >
                  Download
                </Button>
              )}
              {job?.status === 'pending' && job?.generated_by !== currentUserId && !job?.approved_by && (
                <Button
                  variant="default"
                  size="sm"
                  iconName="CheckCircle"
                  onClick={() => onApprove(job?.id)}
                  fullWidth
                >
                  Approve
                </Button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ReportJobsTable;