import React, { useState, useEffect } from 'react';
import Icon from '../../../components/AppIcon';
import Button from '../../../components/ui/Button';
import { reportingService } from '../../../services/reportingService';

const YearEndCertificationCard = ({ organizationId, userId, onApprove }) => {
  const [pendingCertifications, setPendingCertifications] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPendingCertifications = async () => {
      if (!organizationId) {
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        const jobs = await reportingService?.getReportingJobs(organizationId);
        
        // Filter for pending certifications (status = pending and not generated by current user)
        const pending = jobs?.filter(
          job => job?.status === 'pending' && job?.generated_by !== userId && !job?.approved_by
        );
        
        setPendingCertifications(pending);
      } catch (err) {
        console.error('Error fetching pending certifications:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchPendingCertifications();
  }, [organizationId, userId]);

  const handleApprove = async (reportId) => {
    await onApprove(reportId);
    
    // Refresh pending certifications
    const jobs = await reportingService?.getReportingJobs(organizationId);
    const pending = jobs?.filter(
      job => job?.status === 'pending' && job?.generated_by !== userId && !job?.approved_by
    );
    setPendingCertifications(pending);
  };

  return (
    <div className="bg-card rounded-lg border border-border p-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-lg bg-success/10 flex items-center justify-center">
          <Icon name="Award" size={20} className="text-success" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-foreground">Year-End Compliance Certification</h3>
          <p className="text-sm text-muted-foreground">Review and approve year-end compliance reports</p>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-8">
          <Icon name="Loader" size={32} className="animate-spin mx-auto mb-2 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">Loading certifications...</p>
        </div>
      ) : pendingCertifications?.length === 0 ? (
        <div className="text-center py-8">
          <Icon name="CheckCircle" size={48} className="mx-auto mb-4 text-success" />
          <p className="text-sm text-foreground font-medium mb-1">All certifications approved</p>
          <p className="text-sm text-muted-foreground">No pending year-end certifications require your approval</p>
        </div>
      ) : (
        <div className="space-y-4">
          {pendingCertifications?.map((cert) => (
            <div 
              key={cert?.id} 
              className="p-4 bg-muted/30 rounded-lg border border-border"
            >
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                <div className="flex-1">
                  <p className="text-sm font-medium text-foreground mb-1">{cert?.job_name}</p>
                  <p className="text-xs text-muted-foreground mb-2">
                    Generated by: {cert?.generator?.full_name || 'N/A'}
                  </p>
                  <div className="flex items-center gap-2">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-warning/10 text-warning border border-warning">
                      Pending Approval
                    </span>
                    <span className="text-xs text-muted-foreground">
                      Year: {cert?.reporting_years?.year || 'N/A'}
                    </span>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="default"
                    size="sm"
                    iconName="CheckCircle"
                    onClick={() => handleApprove(cert?.id)}
                  >
                    Approve Certification
                  </Button>
                </div>
              </div>
              
              {/* Separation of Duties Notice */}
              <div className="mt-4 p-3 bg-primary/5 border border-primary/20 rounded-md">
                <div className="flex items-start gap-2">
                  <Icon name="Info" size={16} className="text-primary mt-0.5" />
                  <p className="text-xs text-muted-foreground">
                    <span className="font-medium text-foreground">Separation of Duties:</span> You can approve this report because you did not generate it. The system enforces that generated_by cannot equal approved_by.
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default YearEndCertificationCard;